# Generated by Django 4.1 on 2022-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_en',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_fr',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Image'),
        ),
    ]
