# Generated by Django 4.1 on 2022-08-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image_en_profile_image_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_fr',
        ),
    ]
