# Generated by Django 4.1 on 2022-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author_en_post_author_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_fr',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
