# Generated by Django 4.1 on 2022-08-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content_alter_post_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_fr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_fr',
        ),
    ]
